#!/bin/sh
get_corona_us () {
	curl -s -f https://corona-stats.online/states/us -o ~/.cache/corona || get_corona_us
}
get_corona () {
	curl -s -f https://corona-stats.online/"$_location" -o ~/.cache/corona || get_corona
}
log_corona () {
	cat ~/.cache/corona >> ~/.cache/log_corona
}
update_corona () {
	if [ "$(stat -c %y ~/.cache/corona 2>/dev/null | cut -b 1-16)" != "$(date '+%Y-%m-%d %H:%M')" ] ; then
		if [ -z "$usa_state" ] ; then
			get_corona
		else
			get_corona_us
		fi
	fi
}
show_corona () {
	grep -i "$_location" ~/.cache/corona | sed 's/\s*//g ; s/║//g ; s/│/;/g ; s/\x1b\[[0-9;]*m//g ; s/,//g' | awk -F';' '{print "😷" $3 "(" $4") 💀"$5 "(" int(100*(100*$5/$3))/100 "%) ☺" $7 "(" int(100*(100*$7/$3))/100 "%)" }' 2>/dev/null
	[ -z "$_location" ] && grep -i "world" ~/.cache/corona | sed -n 's/\s*//g ; s/║//g ; s/│/;/g ; s/\x1b\[[0-9;]*m//g ; s/,//g ; 2p' | awk -F';' '{print "😷" $3 "(" $4") 💀"$5 "(" int(100*(100*$5/$3))/100 "%) ☺" $7 "(" int(100*(100*$7/$3))/100 "%)" }' 2>/dev/null
}
output_mode () {
	[ -z "$silent_mode" ] && show_corona
}
_Input="$*"
while getopts "hcsnurl" o; do case "${o}" in
	c) client_only="True" ;;
	s) silent_mode="True" ;;
	n) no_log="True" ;;
	u) usa_state="True" ;;
	l) _location="${_Input##*-l }" ;;
	*) printf "Usage: covid [options] -l [string]\\nOptions:\\n   -c: Run as client.\\n   -s: Silence output.\\n   -n: Do not log output.\\n   -u: USA states stats.\\n   -l: enter location as [-l string].\\n   -h: Display this help.\\n" && exit ;;
esac done
if [ -z "$client_only" ] ; then
	update_corona
	output_mode
else
	while true
	do
		output_mode
		sleep 60
	done
fi
[ -z "$no_log" ] && log_corona
